نام شرکت

title: "متادانلود"
نام انگلیسی شرکت

name_en: "metadownload"
دسته‌ی فعالیت شرکت

industry: "کامپیوتر، فناوری اطلاعات و اینترنت"
موقعیت مکانی شرکت

city: "tehran"
تعداد نفرات شرکت

size: "10"
آدرس سایت شرکت

site: "https://www.metadownload.ir"
توضیحی درباره شرکت و فعالیت‌هایش

content: "متا دانلود به عنوان بزرگترین پلتفرم کافی نت آنلاین در ایران شناخته شده است که تعهد خود به اصول اساسی نظیر ضمانت، ایمنی، کیفیت برتر و سرعت در ارائه خدمات را حفظ می‌کند. این مجموعه، طیف گسترده‌ای از خدمات اینترنتی و کافی‌نتی را ارائه می دهد، علاوه بر آن خدمات در حوزه‌های گرافیک، طراحی، تایپ، ترجمه، پروژه، و خدمات برنامه نویسی را با بالاترین سطح کیفیت و در کوتاه‌ترین زمان ممکن به مشتریان خود ارائه می‌دهد.
"
آدرس تصویر لوگوی شرکت

logo: "https://www.metadownload.ir/wp-content/webp-express/webp-images/uploads/2021/09/logo-site-header-file-asli.png.webp"
آدرس تصویر بنر شرکت

cover: ""
